### ISSUE TITLE
Tag/Release when extension is updated on martketplace?

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-vscode#58]
Would it be possible to tag/release the repository when the extension is updated on [marketplace](https://marketplace.visualstudio.com/)?

**Comment by jjallaire** [comment]
Yeah, I need to automate the release process so that this all done in a GH action (haven't had time to do that yet)

**Comment by mcanouil** [comment]
I did not test it, but assuming, you stick with the "release vX.X.X" commit message.
Something like below should do the trick (I can do a PR):

```yaml
n:
  push:
    branches: main

name: Release

jobs:
  create_release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'release')
    steps:
      - uses: actions/checkout@v3
      - name: Set version from commit message
        id: tag_id
        run: |
          VAR="${{ github.event.head_commit.message }}"
          TAG="${VAR#* }"
          echo ::set-output name=tag::"${TAG}"
          echo "${TAG}"
      - name: Set release name
        id: release_id
        run: |
          echo ::set-output name=releasename::"${{ steps.tag_id.outputs.tag }}"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          custom_tag: ${{ steps.tag_id.outputs.tag }}
          tag_prefix: ""
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.release_id.outputs.releasename }}
          generateReleaseNotes: true
          allowUpdates: false
          token: ${{ secrets.GITHUB_TOKEN }}
```
